/**
 * This file was generated by the Jeddict
 */
package com.mobi5.webapp.model;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;

/**
 * @author stibiun
 */
@Entity
public class Student {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    @Basic
    private String name;
    @Basic
    private String birthDate;
    @Basic
    private String picture;
    @ManyToOne(targetEntity = InstitutionUnity.class)
    private InstitutionUnity institutionUnity;
    @ManyToMany(targetEntity = MobileApplicationUser.class, mappedBy = "students")
    private List<MobileApplicationUser> mobileApplicationUsers;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBirthDate() {
        return this.birthDate;
    }

    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }

    public String getPicture() {
        return this.picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

    public InstitutionUnity getInstitutionUnity() {
        return this.institutionUnity;
    }

    public void setInstitutionUnity(InstitutionUnity institutionUnity) {
        this.institutionUnity = institutionUnity;
    }

    public List<MobileApplicationUser> getMobileApplicationUsers() {
        if (mobileApplicationUsers == null) {
            mobileApplicationUsers = new ArrayList<>();
        }
        return this.mobileApplicationUsers;
    }

    public void setMobileApplicationUsers(List<MobileApplicationUser> mobileApplicationUsers) {
        this.mobileApplicationUsers = mobileApplicationUsers;
    }

    public void addMobileApplicationUser(MobileApplicationUser mobileApplicationUser) {
        getMobileApplicationUsers().add(mobileApplicationUser);
    }

    public void removeMobileApplicationUser(MobileApplicationUser mobileApplicationUser) {
        getMobileApplicationUsers().remove(mobileApplicationUser);
    }
}